### ISSUE TITLE
SwiftQRScanner/SwiftQRScanner.swift:36: Fatal error: init(coder:) has not been implemented

### ISSUE THREAD

**Issue by Rajababu6391** [vinodiOS/SwiftQRCodeScanner#16]
add library through pods. facing the issue, Thread 1: Fatal error: init(coder:) has not been implemented

**Comment by jpvinod** [comment]
@Rajababu6391 could you please provide more details like Swift and iOS version? Are you using with storyboard or SwiftUI?
Thank you.

**Comment by Rajababu6391** [comment]
@vinodiOS  using minimum Deployment target ios 13.0 and using a storyboard only.

**Comment by jpvinod** [comment]
@Rajababu6391 Could you please share the code for how you are using it?
