### ISSUE TITLE
'delegate' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by approckw2013** [vinodiOS/SwiftQRCodeScanner#3]
I'm  trying to create scanner obj from you class QRCodeScannerController when set delegate to self i got this issue 'delegate' is inaccessible due to 'internal' protection level

**Comment by jpvinod** [comment]
@approckw2013 use pod 'SwiftQRScanner', :git => ‘https://github.com/vinodiOS/SwiftQRScanner’ in your Podfile. Currently, it referring to older code.
