### ISSUE TITLE
message "Align QR code within frame to scan"

### ISSUE THREAD

**Issue by rfcj** [vinodiOS/SwiftQRCodeScanner#5]
Any possibility to modify this message? I need to translate to another language. Maybe together with the images to modify the ui?

**Comment by jpvinod** [comment]
You can change images but currently know way to change message. I will make provision to change message soon.

**Comment by polis80cy** [comment]
Any luck changing the message or still not an option?

**Comment by jpvinod** [comment]
You can change it now.
