### ISSUE TITLE
UIKit import issue

### ISSUE THREAD

**Issue by pankaj9143** [vinodiOS/SwiftQRCodeScanner#8]
I have implemented your lib in my code using dependencies, but some classes giving me compile time errors, that is because some file does not have UIKit import. Please see above attached screenshot.
![Screenshot 2022-07-14 at 3 45 50 PM](https://user-images.githubusercontent.com/31798316/178959995-71718e70-6503-4356-b28c-c6f66135b094.png)
.

**Comment by jpvinod** [comment]
Are you using SPM?

**Comment by pankaj9143** [comment]
yes, i have added package url to dependencies.

**Comment by jpvinod** [comment]
Currently, SPM support for this library is in process, till then you can use with cocoa pods.

**Comment by pankaj9143** [comment]
I am not using pods for other libraries also, so i can't use (and don't want to use pods). Thanks for reply & your support.

**Comment by jpvinod** [comment]
@pankaj9143 This issue has been resolved. Please give it a try and if you like ✨ the repo.
